variables:
  _JAVA_OPTIONS: "-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"

tag_checker:
  stage: build
  script:
    - python tag_checker.py $CI_COMMIT_TAG
  only:
    - tags

junit:
  stage: test
  script:
    - mvn -B clean test verify sonar:sonar

recent-artifacts:
  stage: deploy
  script:
    - mvn -B clean install site package -Dmaven.test.skip=true

  artifacts:
    paths:
      - target/organz-*-*.jar
    expire_in: 1 week
  except:
    - tags

release-artifacts:
  stage: deploy
  script:
    - mvn -B clean site package
  artifacts:
    paths:
      - target/organz-*-*.jar
      - target/site/jacoco/*
  only:
    - tags
