variables:
  _JAVA_OPTIONS: "-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"

tag_checker:
  stage: build
  script:
    - python tag_checker.py $CI_COMMIT_TAG
  only:
    - tags

junit:
  stage: test
  script:
    - mvn -B clean test

recent-artifacts:
  stage: deploy
  script:
    - mvn -B clean site package -Dmaven.test.skip=true

  artifacts:
    paths:
      - README.md
      - doc/examples/*
      - doc/design_decisions.md
      - doc/test_manual.md
      - doc/User_Manual.pdf
      - target/organz-*-*.jar
    expire_in: 1 week
  except:
    - tags
    - master@seng302-2018/team-700

recent-artifacts-dev:
  stage: deploy
  script:
    - mvn -B clean site package verify sonar:sonar

  artifacts:
    paths:
      - README.md
      - doc/examples/*
      - doc/design_decisions.md
      - doc/test_manual.md
      - doc/User_Manual.pdf
      - target/organz-*-*.jar
    expire_in: 1 week
  only:
    - master@seng302-2018/team-700

server-build-image:
  stage: build
  script:
  - mvn -B clean package -Dmaven.test.skip=true
  - echo $CI_COMMIT_SHA > ./target/version
  - docker-compose build
  only:
  - deployment@seng302-2018/team-700
  - master@seng302-2018/team-700

server-deployment:
  stage: deploy
  script:
  - docker stop team700_web_1 || echo "success"
  - docker container prune -f
  - docker-compose up -d
  only:
  - deployment@seng302-2018/team-700
  - master@seng302-2018/team-700

release-artifacts:
  stage: deploy
  script:
    - mvn -B clean site package
  artifacts:
    paths:
      - target/organz-*-*.jar
      - target/version
      - target/site/jacoco/*
  only:
    - tags
